app_server/django_arena/chatrooms/urls.py
import django.urls

import chatrooms.views

app_name = "chat"

urlpatterns = [
    django.urls.path(
        "<int:pk>/",
        chatrooms.views.GroupChatView.as_view(),
        name="group-chat",
    ),
]

app_server/django_arena/django_arena/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.auth.urls
import django.urls

import chatrooms.urls
import duel.urls
import feedback.urls
import groups.urls
import homepage.urls
import invitations.urls
import lobby.urls
import notes.urls
import notifications.urls
import submissions.urls
import users.urls

urlpatterns = [
    django.urls.path("", django.urls.include(homepage.urls)),
    django.urls.path("users/", django.urls.include(users.urls)),
    django.urls.path(
        "notifications/",
        django.urls.include(notifications.urls),
    ),
    django.urls.path(
        "friends/",
        django.urls.include(invitations.urls),
    ),
    django.urls.path("duel/", django.urls.include(duel.urls)),
    django.urls.path("play/", django.urls.include(lobby.urls)),
    django.urls.path("chat/", django.urls.include(chatrooms.urls)),
    django.urls.path("submissions/", django.urls.include(submissions.urls)),
    django.urls.path("groups/", django.urls.include(groups.urls)),
    django.urls.path("blog/", django.urls.include(notes.urls)),
    django.urls.path("feedback/", django.urls.include(feedback.urls)),
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("i18n/", django.urls.include("django.conf.urls.i18n")),
]

if django.conf.settings.DEBUG:
    urlpatterns += (
        django.urls.path(
            "__debug__/",
            django.urls.include("debug_toolbar.urls"),
        ),
    )
    urlpatterns += django.conf.urls.static.static(
        django.conf.settings.MEDIA_URL,
        document_root=django.conf.settings.MEDIA_ROOT,
    )

__all__ = []

app_server/django_arena/duel/urls.py
import django.urls

import duel.views

app_name = "duel"

urlpatterns = [
    django.urls.re_path(
        r"^(?P<uidb>\w+)/(?P<task_num>\d+)/(?P<tab>description|submissions)/$",
        duel.views.DuelView.as_view(),
        name="duel",
    ),
    django.urls.path(
        "<uidb>/results/",
        duel.views.ResultsView.as_view(),
        name="results",
    ),
    django.urls.path(
        "<uidb>/timeout/",
        duel.views.DuelTimerView.as_view(),
        name="timeout",
    ),
    django.urls.path(
        "<uidb>/leave/",
        duel.views.LeaveDuelView.as_view(),
        name="leave",
    ),
    django.urls.path(
        "cache-code/<uidb>/",
        duel.views.CacheCodeView.as_view(),
        name="cache-code",
    ),
    django.urls.path(
        "cache-result/<uidb>/",
        duel.views.CacheTestsResultView.as_view(),
        name="cache-result",
    ),
]

app_server/django_arena/groups/urls.py
import django.urls

import groups.views

app_name = "groups"


urlpatterns = [
    django.urls.path("my/", groups.views.GroupMyView.as_view(), name="my"),
    django.urls.path("all/", groups.views.GroupAllView.as_view(), name="all"),
    django.urls.path(
        "create/",
        groups.views.GroupCreateView.as_view(),
        name="new_groups",
    ),
    django.urls.path(
        "add/",
        groups.views.GroupEnterUser.as_view(),
        name="enter_user_in_group",
    ),
    django.urls.path(
        "invitations/",
        groups.views.GroupInvitations.as_view(),
        name="invitations",
    ),
    django.urls.path(
        "invite_request/<int:pk>",
        groups.views.GroupInviteRequest.as_view(),
        name="invite_request",
    ),
    django.urls.path(
        "invitations/<int:pk>/",
        groups.views.GroupInviteCard.as_view(),
        name="invite_card",
    ),
    django.urls.path(
        "groups/<int:pk>/",
        groups.views.GroupPage.as_view(),
        name="groups_detail",
    ),
]

app_server/django_arena/invitations/urls.py
import django.urls

import invitations.views


app_name = "invitations"

urlpatterns = [
    django.urls.path(
        "add/",
        invitations.views.SendInvite.as_view(),
        name="add_friend",
    ),
    django.urls.path(
        "invites/",
        invitations.views.Invites.as_view(),
        name="invite_list",
    ),
    django.urls.path(
        "invite_card/<int:pk>",
        invitations.views.InviteCard.as_view(),
        name="invite_card",
    ),
]

app_server/django_arena/invitations/models.py
import django.db.models

import core.models


class InviteModel(django.db.models.Model):
    user_from = django.db.models.ForeignKey(
        core.models.User,
        on_delete=django.db.models.CASCADE,
        related_name="from+",
    )
    user_to = django.db.models.ForeignKey(
        core.models.User,
        on_delete=django.db.models.CASCADE,
        related_name="to+",
    )
    text = django.db.models.CharField(max_length=255)


__all__ = [InviteModel]

app_server/django_arena/groups/forms.py
import django.forms

import groups.models


class BootstrapForm(django.forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            if field.name != "is_public":
                field.field.widget.attrs["class"] = "form-control"


class GroupForm(BootstrapForm, django.forms.ModelForm):
    class Meta:
        model = groups.models.Group
        fields = (
            groups.models.Group.title.field.name,
            groups.models.Group.description.field.name,
            groups.models.Group.theme.field.name,
            groups.models.Group.name.field.name,
            groups.models.Group.is_public.field.name,
            groups.models.Group.image.field.name,
        )


class EnterGroupForm(BootstrapForm, django.forms.ModelForm):
    class Meta:
        model = groups.models.Group
        fields = (groups.models.Group.name.field.name,)
        labels = {
            groups.models.Group.name.field.name: "Название группы",
        }


class InviteGroupForm(BootstrapForm):
    user = django.forms.CharField(max_length=255)
    text = django.forms.CharField(max_length=255)


class AcceptRejectForm(BootstrapForm, django.forms.ModelForm):
    class Meta:
        model = groups.models.GroupInvite
        fields = (groups.models.GroupInvite.accept.field.name,)


class DeleteForm(BootstrapForm):
    is_delete = django.forms.CharField(
        help_text="Напишите слово 'Удалить', чтобы удалить группу",
        label="Удалить группу",
    )


__all__ = [GroupForm, InviteGroupForm, DeleteForm]

app_server/django_arena/invitations/forms.py
import django.forms


class InviteFriendForm(django.forms.Form):
    name = django.forms.CharField(max_length=255, label="Имя пользоавтеля")
    text = django.forms.CharField(
        max_length=255,
        label="Тест приглашения",
    )


class AcceptOrReject(django.forms.Form):
    ANSWER = (
        (0, "Отклонить"),
        (1, "Принять"),
    )
    is_accept = django.forms.ChoiceField(
        choices=ANSWER,
    )


__all__ = [InviteFriendForm]

app_server/django_arena/groups/views.py
import django.contrib.auth.mixins
import django.contrib.messages
import django.core.exceptions
import django.db.models
import django.shortcuts
import django.urls
import django.views

import core.models
import groups.forms
import groups.models


class GroupPage(django.views.View):
    def get(self, *args, **kwargs):
        group = django.shortcuts.get_object_or_404(
            groups.models.Group,
            pk=kwargs.get("pk"),
        )
        try:
            group_user = groups.models.GroupUser.objects.get(
                user_id=self.request.user.id,
                group_id=kwargs.get("pk"),
            )
        except groups.models.GroupUser.DoesNotExist:
            group_user = None

        if self.request.user.is_authenticated:
            context = {
                "title": "Группа",
                "item": kwargs.get("pk"),
                "group": group,
                "delete": groups.forms.DeleteForm(),
                "user": group_user,
            }
            return django.shortcuts.render(
                self.request,
                "group/group.html",
                context,
            )

        django.contrib.messages.info(self.request, "Вы не аутентифицированы")
        return django.shortcuts.redirect(
            django.shortcuts.reverse("homepage:main"),
        )

    def post(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            form = groups.forms.DeleteForm(self.request.POST)
            if form.is_valid():
                if self.request.POST.get("is_delete") == "Удалить":
                    groups.models.Group.objects.get(
                        id=kwargs.get("pk"),
                    ).delete()
                    django.contrib.messages.info(
                        self.request,
                        "Группа успешно удалена",
                    )
                    return django.shortcuts.redirect(
                        django.shortcuts.reverse("homepage:main"),
                    )

            django.contrib.messages.info(self.request, "Форма не валидна")
            return django.shortcuts.redirect(
                django.shortcuts.reverse("homepage:main"),
            )

        django.contrib.messages.info(self.request, "Вы не аутентифицированы")
        return django.shortcuts.redirect(
            django.shortcuts.reverse("homepage:main"),
        )


class GroupMyView(django.views.View):
    def get(self, *args, **kwargs):
        user_groups = self.request.user.group_user.values_list(
            "group",
            flat=True,
        )
        selected_groups = groups.models.Group.objects.filter(
            id__in=user_groups,
        )

        context = {
            "title": "Группы",
            "tab": "my",
            "groups": selected_groups,
        }

        return django.shortcuts.render(
            request=self.request,
            template_name="group/user_group.html",
            context=context,
        )


class GroupAllView(django.views.View):
    def get(self, *args, **kwargs):
        selected_groups = (
            groups.models.Group.objects.all()
            .prefetch_related("group")
            .order_by(
                "-created_at",
            )
        )
        context = {
            "title": "Искать группы",
            "tab": "all",
            "groups": selected_groups,
        }
        return django.shortcuts.render(
            request=self.request,
            template_name="group/user_group.html",
            context=context,
        )


class GroupCreateView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.CreateView,
):
    model = groups.models.Group
    template_name = "group/new_group.html"
    form_class = groups.forms.GroupForm
    success_url = django.urls.reverse_lazy("groups:my")

    def form_valid(self, form):
        self.object = form.save()
        object_id = self.object.id

        groups.models.GroupUser.objects.create(
            user_id=self.request.user.id,
            group_id=object_id,
            leader=1,
            moderator=0,
        )

        return super().form_valid(form)


class GroupEnterUser(django.views.View):
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            context = {
                "title": "Присоединиться к группе",
                "form": groups.forms.EnterGroupForm(),
            }
            return django.shortcuts.render(
                self.request,
                "group/enter_group_name.html",
                context,
            )

        django.contrib.messages.info(self.request, "Вы не аутентифицированы")
        return django.shortcuts.redirect(
            django.shortcuts.reverse("homepage:main"),
        )

    def post(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            context = {
                "title": "Добавить пользователя в группу",
                "form": groups.forms.EnterGroupForm(),
            }
            try:
                group_id = groups.models.Group.objects.get(
                    name=self.request.POST.get("name"),
                ).id
            except django.core.exceptions.ObjectDoesNotExist:
                django.contrib.messages.error(
                    self.request,
                    "Такой группы не существует",
                )
                return django.shortcuts.render(
                    self.request,
                    "group/enter_group_name.html",
                    context,
                )

            if not groups.models.Group.objects.get(id=group_id).is_public:
                django.contrib.messages.error(
                    self.request,
                    "Группа приватная",
                )
                return django.shortcuts.render(
                    self.request,
                    "group/enter_group_name.html",
                    context,
                )

            user_id = self.request.user.id
            try:
                groups.models.GroupUser.objects.get(
                    user_id=user_id,
                    group_id=group_id,
                )
            except django.core.exceptions.ObjectDoesNotExist:
                pass
            else:
                django.contrib.messages.success(
                    self.request,
                    "Пользователь уже состоит в группе",
                )
                return django.shortcuts.redirect(
                    django.shortcuts.reverse("groups:enter_user_in_group"),
                )

            groups.models.GroupUser.objects.create(
                user_id=user_id,
                group_id=group_id,
                leader=0,
                moderator=0,
            )
            django.contrib.messages.success(
                self.request,
                "Вы были добавлены в группу" + self.request.POST.get("name"),
            )
            return django.shortcuts.redirect(
                django.shortcuts.reverse("groups:groups"),
            )

        django.contrib.messages.info(self.request, "Вы не аутентифицированы")
        return django.shortcuts.render(
            self.request,
            "homepage/main.html",
            {"title": "Главная"},
        )


class GroupInvitations(django.views.View):
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            invite = groups.models.GroupInvite.objects.filter(
                user=self.request.user.id,
            )
            context = {
                "title": "Приглашения",
                "invitation": invite.select_related(
                    "group",
                ).only("group_id"),
            }
            return django.shortcuts.render(
                self.request,
                "group/invitations.html",
                context,
            )

        django.contrib.messages.info(self.request, "Вы не аутентифицированы")
        return django.shortcuts.redirect(
            django.shortcuts.reverse("homepage:main"),
        )


class GroupInviteRequest(django.views.View):
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            contex = {
                "title": "Пригласить в группу",
                "form": groups.forms.InviteGroupForm(),
            }
            return django.shortcuts.render(
                self.request,
                "group/invite_request.html",
                contex,
            )

        django.contrib.messages.info(self.request, "Вы не аутентифицированы")
        return django.shortcuts.redirect(
            django.shortcuts.reverse("homepage:main"),
        )

    def post(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            context = {
                "title": "Пригласить в группу",
                "form": groups.forms.InviteGroupForm(),
            }
            form = groups.forms.InviteGroupForm(self.request.POST)
            if form.is_valid():
                try:
                    user = core.models.User.objects.get(
                        username=self.request.POST.get("user"),
                    )
                    group = groups.models.Group.objects.get(
                        id=kwargs.get("pk"),
                    )
                except django.core.exceptions.ObjectDoesNotExist:
                    django.contrib.messages.error(
                        self.request,
                        "Такого пользователя или группы не существует",
                    )
                    return django.shortcuts.render(
                        self.request,
                        "group/invite_request.html",
                        context,
                    )

                user_group = groups.models.GroupUser.objects.get(
                    user_id=self.request.user.id,
                    group_id=kwargs.get("pk"),
                )
                is_leader, is_moderator = (
                    user_group.leader,

app_server/django_arena/templates/group/enter_group_name.html
{% extends "base.html" %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {% include "includes/form.html" %}
    <button type="submit">Отправить</button>
</form>
{% endblock %}

app_server/django_arena/templates/group/group.html
{% extends "base.html" %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
{% if group_user and group_user.leader or user.moderator %}
    <a href="{% url 'groups:invite_request' pk=item %}">Добавить в группу</a>
{% endif %}
<a href={% url "chat:group-chat" group.chat.id %}>Групповой чат</a>
{% if group_user and group_user.leader %}
    <form method="post">
        {% csrf_token %}
        {{ delete }}
        <button type="submit">Удалить</button>
    </form>
{% endif %}
{% endblock %}

app_server/django_arena/templates/group/invitations.html
{% extends "base.html" %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
{% for item in invitation %}
    <a href="{% url 'groups:invite_card' pk=item.group_id %}">{{ item.group.name }}</a>
{% endfor %}
{% endblock %}

app_server/django_arena/templates/group/invite_card.html
{% extends "base.html" %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ context }}
    {% include "includes/form.html" %}
    <button type="submit">Отправить</button>
</form>
{% endblock %}

app_server/django_arena/templates/group/invite_request.html
{% extends "base.html" %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {% include "includes/form.html" %}
    <button type="submit">Отправить</button>
</form>
{% endblock %}

app_server/django_arena/templates/group/new_group.html
{% extends "base.html" %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
<div class="container py-5 h-100 w-50">
    <div class="card shadow-2-strong bg-dark" style="border-radius: 1rem;">
        <div class="card-body p-5" style="color: #DCDCDC">
            <h2 class="text-center">Создание группы</h2>
            <form method="post" enctype="multipart/form-data">
                {% with form=form %}
                  {% include "includes/form.html" %}
                {% endwith %}
                <button style="width: 100%" type="submit" class="btn btn-outline-light mb-2 mt-1">Создать</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app_server/django_arena/templates/group/user_group.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{{ title }}
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <ul class="nav nav-tabs" style="border: none;margin-bottom: -2px">
            <li class="nav-item">
                <a class="nav-link" {% if tab == "all" %}style="background-color: #343a39;border:none" {% else %}
                    style="border:none" {% endif %} href={% url "groups:all" %}>Искать</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" {% if tab == "my" %}style="background-color: #343a39;border: none;" {% else %}
                    style="border:none" {% endif %} href={% url "groups:my" %}>Мои группы</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="border:none"  href={% url "groups:new_groups" %}>Создать</a>
            </li>
        </ul>
        <div class="card" id="parent_card">
            <div class="card-body">
                {% for group in groups %}
                <a href="{% url 'groups:groups_detail' group.id %}" style="text-decoration:none">{% include "includes/group.html" %}</a>
                {% empty %}
                <div class="no-posts">
                    <img id="raccoon" alt="" src="{% static "images/sad-raccoon.png" %}" height="170" loading="lazy">
                    <div>
                        <p><span style="color: #74decb">В</span>ы не состоите ни в одной группе! Беда! Срочно ищите
                            сообщество по интересам или создайте свое!</p>
                        <a href={% url "groups:new_groups" %}><button class="create-post-btn btn btn-primary">Создать
                                группу</button></a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}