app_server/django_arena/django_arena/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.auth.urls
import django.urls

import chatrooms.urls
import duel.urls
import feedback.urls
import groups.urls
import homepage.urls
import invitations.urls
import lobby.urls
import notes.urls
import notifications.urls
import submissions.urls
import users.urls

urlpatterns = [
    django.urls.path("", django.urls.include(homepage.urls)),
    django.urls.path("users/", django.urls.include(users.urls)),
    django.urls.path(
        "notifications/",
        django.urls.include(notifications.urls),
    ),
    django.urls.path(
        "friends/",
        django.urls.include(invitations.urls),
    ),
    django.urls.path("duel/", django.urls.include(duel.urls)),
    django.urls.path("play/", django.urls.include(lobby.urls)),
    django.urls.path("chat/", django.urls.include(chatrooms.urls)),
    django.urls.path("submissions/", django.urls.include(submissions.urls)),
    django.urls.path("groups/", django.urls.include(groups.urls)),
    django.urls.path("blog/", django.urls.include(notes.urls)),
    django.urls.path("feedback/", django.urls.include(feedback.urls)),
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("i18n/", django.urls.include("django.conf.urls.i18n")),
]

if django.conf.settings.DEBUG:
    urlpatterns += (
        django.urls.path(
            "__debug__/",
            django.urls.include("debug_toolbar.urls"),
        ),
    )
    urlpatterns += django.conf.urls.static.static(
        django.conf.settings.MEDIA_URL,
        document_root=django.conf.settings.MEDIA_ROOT,
    )

__all__ = []

app_server/django_arena/duel/urls.py
import django.urls

import duel.views

app_name = "duel"

urlpatterns = [
    django.urls.re_path(
        r"^(?P<uidb>\w+)/(?P<task_num>\d+)/(?P<tab>description|submissions)/$",
        duel.views.DuelView.as_view(),
        name="duel",
    ),
    django.urls.path(
        "<uidb>/results/",
        duel.views.ResultsView.as_view(),
        name="results",
    ),
    django.urls.path(
        "<uidb>/timeout/",
        duel.views.DuelTimerView.as_view(),
        name="timeout",
    ),
    django.urls.path(
        "<uidb>/leave/",
        duel.views.LeaveDuelView.as_view(),
        name="leave",
    ),
    django.urls.path(
        "cache-code/<uidb>/",
        duel.views.CacheCodeView.as_view(),
        name="cache-code",
    ),
    django.urls.path(
        "cache-result/<uidb>/",
        duel.views.CacheTestsResultView.as_view(),
        name="cache-result",
    ),
]

app_server/django_arena/notes/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.auth.urls
import django.urls

import notes.views

app_name = "notes"

urlpatterns = [
    django.urls.path(
        "<int:pk>/",
        notes.views.NoteDetailView.as_view(),
        name="detail",
    ),
    django.urls.path(
        "all/",
        notes.views.NoteListAllView.as_view(),
        name="blog-all",
    ),
    django.urls.path(
        "my/",
        notes.views.NoteListMyView.as_view(),
        name="blog-my",
    ),
    django.urls.path(
        "like/",
        notes.views.NoteLikeView.as_view(),
        name="like",
    ),
    django.urls.path(
        "dislike/",
        notes.views.NoteDislikeView.as_view(),
        name="dislike",
    ),
    django.urls.path(
        "create/",
        notes.views.NoteCreateView.as_view(),
        name="create",
    ),
    django.urls.path(
        "update/<int:pk>",
        notes.views.NoteUpdateView.as_view(),
        name="update",
    ),
    django.urls.path(
        "delete/<int:pk>",
        notes.views.NoteDeleteView.as_view(),
        name="delete",
    ),
]


__all__ = []

app_server/django_arena/notes/models.py
import django.db.models

import core.models


class Note(django.db.models.Model):
    title = django.db.models.CharField(max_length=255)
    text = django.db.models.TextField()
    created_at = django.db.models.DateTimeField(
        auto_now_add=True,
    )
    updated_at = django.db.models.DateTimeField(
        auto_now=True,
    )
    author = django.db.models.ForeignKey(
        core.models.User,
        related_name="notes",
        related_query_name="notes",
        on_delete=django.db.models.CASCADE,
    )
    likes = django.db.models.IntegerField(
        default=0,
    )
    dislikes = django.db.models.IntegerField(
        default=0,
    )
    is_on_main = django.db.models.BooleanField(
        default=False,
    )
    official_documentation = django.db.models.BooleanField(
        default=False,
    )
    user_likes = django.db.models.ManyToManyField(
        core.models.User,
        related_name="note_likes",
    )
    user_dislikes = django.db.models.ManyToManyField(
        core.models.User,
        related_name="note_dislikes",
    )

    class Meta:
        verbose_name = "пост"
        verbose_name_plural = "посты"


__all__ = [Note]

app_server/django_arena/notes/forms.py
import django.forms

import notes.models


class BootstrapForm(django.forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"


class NoteForm(BootstrapForm):
    """Form for creating posts"""

    class Meta:
        model = notes.models.Note
        fields = ("title", "text")


__all__ = []

app_server/django_arena/notes/views.py
import django.contrib.auth.mixins
import django.http
import django.shortcuts
import django.urls
import django.views.generic

import core.models
import notes.forms
import notes.models


class NoteListAllView(django.views.generic.ListView):
    model = notes.models.Note
    template_name = "notes/note_list.html"
    context_object_name = "notes"
    ordering = ["-created_at"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tab"] = "all"
        context["title"] = "Блог: популярное"
        return context


class NoteListMyView(django.views.generic.ListView):
    model = notes.models.Note
    template_name = "notes/note_list.html"
    context_object_name = "notes"
    ordering = ["-created_at"]

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(author_id=self.request.user.id).order_by(
            "-created_at",
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tab"] = "my"
        context["title"] = "Блог: мои посты"
        return context


class NoteDetailView(django.views.generic.DetailView):
    model = notes.models.Note
    template_name = "notes/note_detail.html"
    context_object_name = "note"


class NoteCreateView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.CreateView,
):
    model = notes.models.Note
    template_name = "notes/note_create.html"
    form_class = notes.forms.NoteForm
    success_url = django.urls.reverse_lazy("notes:blog-my")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class NoteUpdateView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.contrib.auth.mixins.UserPassesTestMixin,
    django.views.generic.UpdateView,
):
    model = notes.models.Note
    template_name = "notes/note_create.html"
    form_class = notes.forms.NoteForm
    pk_url_kwarg = "pk"
    success_url = django.urls.reverse_lazy("notes:blog-my")

    def test_func(self):
        note = self.get_object()
        return self.request.user == note.author


class NoteDeleteView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.contrib.auth.mixins.UserPassesTestMixin,
    django.views.generic.DeleteView,
):
    model = notes.models.Note
    template_name = "notes/note_confirm_delete.html"
    pk_url_kwarg = "pk"
    success_url = django.urls.reverse_lazy("notes:blog-my")

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


class NoteLikeView(django.views.View):
    def post(self, *args, **kwargs):
        note_id = self.request.POST.get("note_id")
        user_id = self.request.POST.get("user_id")
        note = notes.models.Note.objects.get(id=note_id)
        user = core.models.User.objects.get(id=user_id)
        if notes.models.Note.objects.filter(
            id=note.id,
            user_dislikes__id=user.id,
        ).exists():
            note.user_dislikes.remove(user)
            note.dislikes -= 1
            note.save()

        if notes.models.Note.objects.filter(
            id=note.id,
            user_likes__id=user.id,
        ).exists():
            return django.http.HttpResponse("Already liked", status=400)

        note.user_likes.add(user)
        note.likes += 1
        note.save()
        return django.http.HttpResponse("Liked successfully", status=200)


class NoteDislikeView(django.views.View):
    def post(self, *args, **kwargs):
        note_id = self.request.POST.get("note_id")
        user_id = self.request.POST.get("user_id")
        note = notes.models.Note.objects.get(id=note_id)
        user = core.models.User.objects.get(id=user_id)
        if notes.models.Note.objects.filter(
            id=note.id,
            user_likes__id=user.id,
        ).exists():
            note.user_likes.remove(user)
            note.likes -= 1
            note.save()

        if notes.models.Note.objects.filter(
            id=note.id,
            user_dislikes__id=user.id,
        ).exists():
            return django.http.HttpResponse("Already disliked", status=400)

        note.user_dislikes.add(user)
        note.dislikes += 1
        note.save()
        return django.http.HttpResponse("Disliked successfully", status=200)


__all__ = []

app_server/django_arena/templates/notes/note_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="no-posts">
    <img id="raccoon" alt="" src={% static "images/sad-raccoon.png" %} height="170" loading="lazy">
    <div>
        <p><span style="color: #74decb">В</span>ы уверены, что хотите удалить пост?</p>
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="action" value="confirm_delete">
            <button type="submit" class="create-post-btn btn btn-primary">Да, удалить пост</button>
            <a href="{% url 'notes:blog-my' %}"><button class="create-post-btn btn btn-primary">Не надо</button></a>
          </form>
    </div>
</div>
{% endblock %}

app_server/django_arena/templates/notes/note_create.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <h1>{{ user.username }}</h1>
  <form method="post" enctype="multipart/form-data">
      {% include "includes/form.html" %}
    <button type="submit">Опубликовать</button>
  </form>
{% endblock content %}

app_server/django_arena/templates/notes/note_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{ title }}
{% endblock %}
{% block content %}
  <h1>{{ note.title }}</h1>
  <p>{{ note.text }}</p> 
  {% if request.user.id == note.author.id %}
    <a href={% url "notes:update" note.id %}><button class="create-post-btn btn btn-primary">Редактировать</button></a>
    <a href={% url "notes:delete" note.id %}><button class="btn btn-outline-danger">Удалить</button></a>
  {% endif %}
  {% if request.user.is_authenticated and request.user.id != note.author.id %}
    <form class="like-form" method="post">
      {% csrf_token %}
      <input type="hidden" name="note_id" value="{{ note.id }}">
      <input type="hidden" name="user_id" value="{{ user.id }}">
      <button class="like-form__button"
              value="submit" type="submit">
        <img src="{% static "images/icons/blog_like.svg" %}" width="50"  alt="">
      </button>
    </form>
    <form class="dislike-form" method="post">
      {% csrf_token %}
      <input type="hidden" name="note_id" value="{{ note.id }}">
      <input type="hidden" name="user_id" value="{{ user.id }}">
      <button class="dislike-form__button"
              value="submit" type="submit">
        <img src="{% static "images/icons/blog_dislike.svg" %}" width="50"  alt="">
      </button>
    </form>
  {% endif %}
  <script>
      document.querySelectorAll(".like-form").forEach((el) => { el.addEventListener("submit", function(event) {
          event.preventDefault();
          var formData = new FormData(this);
          var xhr = new XMLHttpRequest();
          xhr.open("POST", "{% url 'notes:like' %}", true);
          xhr.onload = function() {
              if (xhr.status === 200) {
                  console.log(xhr.responseText);
              } else {
                  console.error('Request failed: ' + xhr.status);
              }
          };
          xhr.send(formData);
      })});
      document.querySelectorAll(".dislike-form").forEach((el) => { el.addEventListener("submit", function(event) {
          event.preventDefault();
          var formData = new FormData(this);
          var xhr = new XMLHttpRequest();
          xhr.open("POST", "{% url 'notes:dislike' %}", true);
          xhr.onload = function() {
              if (xhr.status === 200) {
                  console.log(xhr.responseText);
              } else {
                  console.error('Request failed: ' + xhr.status);
              }
          };
          xhr.send(formData);
      })});
  </script>
{% endblock %}

app_server/django_arena/templates/notes/note_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{{ title }}
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <h1 class="blog-title">Arena<span>Blog<span></h1>
        <ul class="nav nav-tabs" style="border: none;margin-bottom: -2px">
            <li class="nav-item">
                <a class="nav-link" {% if tab == "all" %}style="background-color: #343a39;border:none" {% else %}
                    style="border:none" {% endif %} href={% url "notes:blog-all" %}>Популярное</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" {% if tab == "my" %}style="background-color: #343a39;border: none;" {% else %}
                    style="border:none" {% endif %} href={% url "notes:blog-my" %}>Мои посты</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="border:none" href={% url "notes:create" %}>Создать публикацию</a>
            </li>
        </ul>
        <div class="card" id="parent_card">
            <div class="card-body">
                {% for note in notes %}
                <a style="text-decoration:none" href={% url "notes:detail" note.id %}>{% include "includes/note.html" %}</a>
                {% empty %}
                <div class="no-posts">
                    <img id="raccoon" alt="" src={% static "images/sad-raccoon.png" %} height="170" loading="lazy">
                    <div>
                        <p><span style="color: #74decb">Е</span>нот грустит без новых знаний( Поделитесь своим опытом!
                            Опубликуйте первый пост!</p>
                        <a href={% url "notes:create" %}><button class="create-post-btn btn btn-primary">Создать
                                публикацию</button></a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <script>
      document.querySelectorAll(".like-form").forEach((el) => { el.addEventListener("submit", function(event) {
          event.preventDefault();
          var formData = new FormData(this);
          var xhr = new XMLHttpRequest();
          xhr.open("POST", "{% url 'notes:like' %}", true);
          xhr.onload = function() {
              if (xhr.status === 200) {
                  console.log(xhr.responseText);
              } else {
                  console.error('Request failed: ' + xhr.status);
              }
          };
          xhr.send(formData);
      })});
      document.querySelectorAll(".dislike-form").forEach((el) => { el.addEventListener("submit", function(event) {
          event.preventDefault();
          var formData = new FormData(this);
          var xhr = new XMLHttpRequest();
          xhr.open("POST", "{% url 'notes:dislike' %}", true);
          xhr.onload = function() {
              if (xhr.status === 200) {
                  console.log(xhr.responseText);
              } else {
                  console.error('Request failed: ' + xhr.status);
              }
          };
          xhr.send(formData);
      })});
    </script>
</div>
{% endblock %}