app_server/django_arena/django_arena/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.auth.urls
import django.urls

import chatrooms.urls
import duel.urls
import feedback.urls
import groups.urls
import homepage.urls
import invitations.urls
import lobby.urls
import notes.urls
import notifications.urls
import submissions.urls
import users.urls

urlpatterns = [
    django.urls.path("", django.urls.include(homepage.urls)),
    django.urls.path("users/", django.urls.include(users.urls)),
    django.urls.path(
        "notifications/",
        django.urls.include(notifications.urls),
    ),
    django.urls.path(
        "friends/",
        django.urls.include(invitations.urls),
    ),
    django.urls.path("duel/", django.urls.include(duel.urls)),
    django.urls.path("play/", django.urls.include(lobby.urls)),
    django.urls.path("chat/", django.urls.include(chatrooms.urls)),
    django.urls.path("submissions/", django.urls.include(submissions.urls)),
    django.urls.path("groups/", django.urls.include(groups.urls)),
    django.urls.path("blog/", django.urls.include(notes.urls)),
    django.urls.path("feedback/", django.urls.include(feedback.urls)),
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("i18n/", django.urls.include("django.conf.urls.i18n")),
]

if django.conf.settings.DEBUG:
    urlpatterns += (
        django.urls.path(
            "__debug__/",
            django.urls.include("debug_toolbar.urls"),
        ),
    )
    urlpatterns += django.conf.urls.static.static(
        django.conf.settings.MEDIA_URL,
        document_root=django.conf.settings.MEDIA_ROOT,
    )

__all__ = []

app_server/django_arena/duel/urls.py
import django.urls

import duel.views

app_name = "duel"

urlpatterns = [
    django.urls.re_path(
        r"^(?P<uidb>\w+)/(?P<task_num>\d+)/(?P<tab>description|submissions)/$",
        duel.views.DuelView.as_view(),
        name="duel",
    ),
    django.urls.path(
        "<uidb>/results/",
        duel.views.ResultsView.as_view(),
        name="results",
    ),
    django.urls.path(
        "<uidb>/timeout/",
        duel.views.DuelTimerView.as_view(),
        name="timeout",
    ),
    django.urls.path(
        "<uidb>/leave/",
        duel.views.LeaveDuelView.as_view(),
        name="leave",
    ),
    django.urls.path(
        "cache-code/<uidb>/",
        duel.views.CacheCodeView.as_view(),
        name="cache-code",
    ),
    django.urls.path(
        "cache-result/<uidb>/",
        duel.views.CacheTestsResultView.as_view(),
        name="cache-result",
    ),
]

app_server/django_arena/submissions/urls.py
import django.urls

import submissions.views

app_name = "submissions"

urlpatterns = [
    django.urls.path(
        "",
        submissions.views.SubmissionListView.as_view(),
        name="submission-list",
    ),
    django.urls.path(
        "<int:pk>/",
        submissions.views.SubmissionDetailView.as_view(),
        name="submission-detail",
    ),
]

__all__ = []

app_server/django_arena/submissions/models.py
import django.conf
import django.core.validators
import django.db.models

import duel.models
import problems.models


class Submission(django.db.models.Model):
    code = django.db.models.TextField()

    score = django.db.models.IntegerField(
        "Оценка",
        null=True,
        blank=True,
        validators=[
            django.core.validators.MaxValueValidator(100),
            django.core.validators.MinValueValidator(1),
        ],
    )

    created_at = django.db.models.DateTimeField(
        "Дата создания",
        auto_now=True,
    )

    problem = django.db.models.ForeignKey(
        problems.models.Problem,
        on_delete=django.db.models.CASCADE,
        related_name="submissions",
        related_query_name="submissions",
    )

    duel = django.db.models.ForeignKey(
        duel.models.Duel,
        on_delete=django.db.models.CASCADE,
        related_name="submissions",
        related_query_name="submissions",
    )

    user = django.db.models.ForeignKey(
        django.conf.settings.AUTH_USER_MODEL,
        on_delete=django.db.models.CASCADE,
        related_name="submissions",
        related_query_name="submissions",
    )

    exec_time = django.db.models.IntegerField(
        "Время выполнения",
        default=-1,
    )

    verdict = django.db.models.CharField(
        "Вердикт",
        max_length=127,
        default="",
    )

    def __str__(self):
        return f"{self.problem.title}"

    class Meta:
        verbose_name = "Решение"
        verbose_name_plural = "Решения"


__all__ = [Submission]

app_server/django_arena/submissions/views.py
import django.contrib.auth.mixins
import django.views.generic

import submissions.models


class SubmissionListView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.ListView,
):
    template_name = "submissions/submission-list.html"
    context_object_name = "submissions"
    model = submissions.models.Submission

    def get_queryset(self):
        return submissions.models.Submission.objects.filter(
            user_id=self.request.user.id,
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Ваши решения"
        return context


class SubmissionDetailView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.DetailView,
):
    template_name = "submissions/submission-detail.html"
    context_object_name = "submission"
    pk_url_kwarg = "pk"
    model = submissions.models.Submission

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = f"Решение номер {self.object.id}"
        return context


__all__ = [SubmissionListView, SubmissionDetailView]

app_server/django_arena/templates/submissions/submission-detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ title }}
{% endblock %}

{% block content %}
  <div>
    <h1 style="text-align:center">{{ title }}</h1>
    <hr>
    <div class="row">
          <p>{{ submission.created_at }}</p>
          <p>Оценка: {{ submission.score }}/100</p>
          <textarea id="id_code">{{ submission.code }}</textarea>
    </div>
  </div>

<script>var editor = CodeMirror.fromTextArea(document.getElementById("id_code"), {
    mode: "python",
    lineNumbers: true,
    autoCloseBrackets: true,
    matchBrackets: true,
    lineWrapping: true,
    indentUnit: 4,
    theme: "dracula",
  });</script>

{% endblock content %}

app_server/django_arena/templates/submissions/submission-list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
<div>
    <h1 style="text-align:center">{{ title }}</h1>
    <hr>
    <div class="row">
        {% for sb in submissions %}
        <a href="{% url "submissions:submission-detail" sb.id %}" style="text-decoration:none;">
            <p>{{ sb.created_at }}</p>
            <p>Оценка: {{ sb.score }}/100</p>
            <textarea id="id_code_{{ sb.id }}">{{ sb.code }}</textarea>
        </a>
        <script>
            var editor = CodeMirror.fromTextArea(document.getElementById("id_code_{{ sb.id }}"), {
                mode: "python",
                lineNumbers: true,
                autoCloseBrackets: true,
                matchBrackets: true,
                lineWrapping: true,
                indentUnit: 4,
                theme: "dracula",
            });
        </script>
        {% empty %}
        <p>У вас пока нет решений</p>
        {% endfor %}
    </div>
</div>
{% endblock content %}