app_server/django_arena/django_arena/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.auth.urls
import django.urls

import chatrooms.urls
import duel.urls
import feedback.urls
import groups.urls
import homepage.urls
import invitations.urls
import lobby.urls
import notes.urls
import notifications.urls
import submissions.urls
import users.urls

urlpatterns = [
    django.urls.path("", django.urls.include(homepage.urls)),
    django.urls.path("users/", django.urls.include(users.urls)),
    django.urls.path(
        "notifications/",
        django.urls.include(notifications.urls),
    ),
    django.urls.path(
        "friends/",
        django.urls.include(invitations.urls),
    ),
    django.urls.path("duel/", django.urls.include(duel.urls)),
    django.urls.path("play/", django.urls.include(lobby.urls)),
    django.urls.path("chat/", django.urls.include(chatrooms.urls)),
    django.urls.path("submissions/", django.urls.include(submissions.urls)),
    django.urls.path("groups/", django.urls.include(groups.urls)),
    django.urls.path("blog/", django.urls.include(notes.urls)),
    django.urls.path("feedback/", django.urls.include(feedback.urls)),
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("i18n/", django.urls.include("django.conf.urls.i18n")),
]

if django.conf.settings.DEBUG:
    urlpatterns += (
        django.urls.path(
            "__debug__/",
            django.urls.include("debug_toolbar.urls"),
        ),
    )
    urlpatterns += django.conf.urls.static.static(
        django.conf.settings.MEDIA_URL,
        document_root=django.conf.settings.MEDIA_ROOT,
    )

__all__ = []

app_server/django_arena/duel/urls.py
import django.urls

import duel.views

app_name = "duel"

urlpatterns = [
    django.urls.re_path(
        r"^(?P<uidb>\w+)/(?P<task_num>\d+)/(?P<tab>description|submissions)/$",
        duel.views.DuelView.as_view(),
        name="duel",
    ),
    django.urls.path(
        "<uidb>/results/",
        duel.views.ResultsView.as_view(),
        name="results",
    ),
    django.urls.path(
        "<uidb>/timeout/",
        duel.views.DuelTimerView.as_view(),
        name="timeout",
    ),
    django.urls.path(
        "<uidb>/leave/",
        duel.views.LeaveDuelView.as_view(),
        name="leave",
    ),
    django.urls.path(
        "cache-code/<uidb>/",
        duel.views.CacheCodeView.as_view(),
        name="cache-code",
    ),
    django.urls.path(
        "cache-result/<uidb>/",
        duel.views.CacheTestsResultView.as_view(),
        name="cache-result",
    ),
]

app_server/django_arena/groups/urls.py
import django.urls

import groups.views

app_name = "groups"


urlpatterns = [
    django.urls.path("my/", groups.views.GroupMyView.as_view(), name="my"),
    django.urls.path("all/", groups.views.GroupAllView.as_view(), name="all"),
    django.urls.path(
        "create/",
        groups.views.GroupCreateView.as_view(),
        name="new_groups",
    ),
    django.urls.path(
        "add/",
        groups.views.GroupEnterUser.as_view(),
        name="enter_user_in_group",
    ),
    django.urls.path(
        "invitations/",
        groups.views.GroupInvitations.as_view(),
        name="invitations",
    ),
    django.urls.path(
        "invite_request/<int:pk>",
        groups.views.GroupInviteRequest.as_view(),
        name="invite_request",
    ),
    django.urls.path(
        "invitations/<int:pk>/",
        groups.views.GroupInviteCard.as_view(),
        name="invite_card",
    ),
    django.urls.path(
        "groups/<int:pk>/",
        groups.views.GroupPage.as_view(),
        name="groups_detail",
    ),
]

app_server/django_arena/users/urls.py
import django.contrib.auth
import django.urls

import users.forms
import users.views

app_name = "users"


def set_form(form):
    return users.forms.set_custom_form(form)


login_view = users.views.CustomLoginView.as_view(
    template_name="users/login.html",
    form_class=set_form(users.forms.CustomAuthenticationForm),
)

logout_view = django.contrib.auth.views.LogoutView.as_view(
    template_name="users/logout.html",
)

urlpatterns = [
    django.urls.path(
        "<int:user_id>/",
        users.views.ProfileView.as_view(),
        name="profile",
    ),
    django.urls.path(
        "friends/",
        users.views.FriendsView.as_view(),
        name="friends",
    ),
    django.urls.path("login/", login_view, name="login"),
    django.urls.path(
        "signup/",
        users.views.SignupView.as_view(),
        name="signup",
    ),
    django.urls.path(
        "edit/",
        users.views.EditUserProfileView.as_view(),
        name="edit",
    ),
    django.urls.path("logout/", logout_view, name="logout"),
]


__all__ = []

app_server/django_arena/templates/chat/group-chat.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="chat container">
  <div class="chat-card card">
    <nav class="chat-nav navbar navbar-expand-lg navbar-dark">
      <div class="container-fluid">
        <a class="chat-title navbar-brand" href="{% url "groups:groups_detail" chat.group.id %}"><img id="ava" alt=""
          src={% if group.image %}"{{ group.image.url }}"{% else %}{% static "images/group-avatar2.jpg" %}{% endif %} height="50" width="50" loading="lazy" class="rounded-circle">
          {{ chat.group.title }}</a>
      </div>
    </nav>
    <div class="messages" id="messages">
      {% for message in messages %}
      {% ifchanged message.created_at|date:"F j, Y" %}
      <div class="message-date"><span>{{ message.created_at|date:"F j, Y" }}</span></div>
      {% endifchanged %}
      <div class="chat-item {% if message.user.id == request.user.id %} my-message {% endif %}">
        <img id="ava" class="social-profile__image rounded-circle" alt=""
                src={% if message.user.image %}"{{ message.user.image.url }}"{% else %}{% static "images/avatar.png" %}{% endif %}
                loading="lazy">
        <div class="message-card card">
          <div><a class="chat-title navbar-brand" href="{% url "users:profile" message.user.id %}">{{ message.user.username }}</a>
            <span class="msg-date">{{ message.created_at|date:"g:i a" }}</span></div>
          <p class="message-text">
            {{ message.content }}
          </p>
        </div>
      </div>
      {% endfor %}
    </div>

    <form method="post" enctype="multipart/form-data">
      <div class="input-group mb-3">
        <input id="message-input" type="text" class="form-control" placeholder="Имя получателя" aria-label="Имя получателя" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button type="submit" id="send-message-button" class="btn btn-outline-secondary" type="button">"Отправить"</button>
        </div>
      </div>
    </form>
  </div>
</div>

<script>
  const cur_url = new URL(window.location.href);
  const path = cur_url.pathname;
  const pathComponents = path.split("/");
  const roomId = pathComponents[pathComponents.length - 2];
  const user_id = {{request.user.id}}
  const currentDate = new Date().toLocaleString();

  const dateObject = new Date();
  const hours = dateObject.getHours();
  const minutes = dateObject.getMinutes().toString().padStart(2, "0");
  const ampm = hours >= 12 ? "p.m." : "a.m.";
  const formattedTime = `${hours % 12 || 12}:${minutes} ${ampm}`;

  let profileUrl = '{% url "users:profile" request.user.id %}';

  var ava_url = "{% static 'images/avatar.png' %}";

  {% if request.user.image %}
    ava_url = "{{ request.user.image.url }}"; 
  {% endif %}
  
  const username = "{{request.user.username}}"

  const chatSocket = new WebSocket(
    "ws://" + window.location.host + "/chat" + `/${roomId}/`
  );

  chatSocket.onmessage = function (e) {
    console.log("chat onmessage");
    const data = JSON.parse(e.data);
    if (data.message) {
      let html = '<div class="chat-item ' + (data.user_id == user_id ? 'my-message' : '') + '">';
      html+= '<img id="ava" alt="" src=' + ava_url + ' class="rounded-circle">'
      html += '<div class="message-card card">';
      html += '<div><a class="chat-title navbar-brand" href="' + profileUrl + '">';
      html += data.username + '</a>' + '<span class="msg-date">' + formattedTime + '</span></div>';
      html += '<p class="message-text">' + data.message + '</p></div></div>'

      document.querySelector("#messages").innerHTML += html;

      scrollToBottom();
    } else {
      console.log("empty message!")
    }
  };

  chatSocket.onclose = function (e) {
    console.error("Chat socket closed unexpectedly");
  };

  document.querySelector('#send-message-button').onclick = function (e) {
    e.preventDefault();
    const messageInputDom = document.querySelector('#message-input')
    const message = messageInputDom.value
    chatSocket.send(JSON.stringify({
      "message": message,
      "user_id": user_id,
      "username": username,
      "room": roomId,
    }));

    messageInputDom.value = '';
    return false
  };

  function scrollToBottom() {
    const objDiv = document.querySelector("#messages")
    objDiv.scrollTop = objDiv.scrollHeight;
  }

  scrollToBottom();
</script>
{% endblock %}